modLoader="javafml"
loaderVersion="${loader_version}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_display_url}"
logoFile="chipscurioslight.png"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.chipscurioslight]]
    modId="neoforge"
    type="required"
    versionRange = "${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.chipscurioslight]]
    modId="minecraft"
    type="required"
    versionRange = "${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
# Curios Dependency
[[dependencies.chipscurioslight]]
    modId="curios"
    type="required"
    versionRange = "[${curios_version},)"
    ordering="NONE"
    side="BOTH"
# Ryoamic Dependency
[[dependencies.chipscurioslight]]
    modId="ryoamiclights"
    type="required"
    versionRange = "[${ryoamiclights_version},)"
    ordering="NONE"
    side="BOTH"
